# Generated by Django 6.0.6 on 2026-06-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_student_paid_student_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
